M48
; DRILL file {KiCad 8.0.2} date 2024-05-30T02:20:03-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-30T02:20:03-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.300
%
G90
G05
T1
X119.33Y-146.73
T2
X90.427Y-111.183
T2
G00X90.427Y-126.533
M15
G01X90.427Y-123.833
M16
G05
M30
